# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(784, 588)
        MainWindow.setStyleSheet("background-color: rgb(85, 0, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.svm_b = QtWidgets.QPushButton(self.centralwidget)
        self.svm_b.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.svm_b.setObjectName("svm_b")
        self.gridLayout.addWidget(self.svm_b, 5, 0, 1, 1)
        self.fuzzy = QtWidgets.QPushButton(self.centralwidget)
        self.fuzzy.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.fuzzy.setObjectName("fuzzy")
        self.gridLayout.addWidget(self.fuzzy, 3, 0, 1, 1)
        self.view = QtWidgets.QPushButton(self.centralwidget)
        self.view.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.view.setObjectName("view")
        self.gridLayout.addWidget(self.view, 2, 0, 1, 1)
        self.network = QtWidgets.QPushButton(self.centralwidget)
        self.network.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.network.setObjectName("network")
        self.gridLayout.addWidget(self.network, 4, 0, 1, 1)
        self.browse = QtWidgets.QPushButton(self.centralwidget)
        self.browse.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.browse.setObjectName("browse")
        self.gridLayout.addWidget(self.browse, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 784, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.svm_b.setText(_translate("MainWindow", "SVM"))
        self.fuzzy.setText(_translate("MainWindow", "Fuzzy-Clustering"))
        self.view.setText(_translate("MainWindow", "View"))
        self.network.setText(_translate("MainWindow", "M-C Neural Network"))
        self.browse.setText(_translate("MainWindow", "Browse"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
